CREATE TABLE IF NOT EXISTS devices (
    id SERIAL PRIMARY KEY,
    eui VARCHAR(255) NOT NULL,
    long DOUBLE PRECISION NOT NULL,
    lat DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS sensor_data (
    id SERIAL PRIMARY KEY,
    device_id INTEGER REFERENCES devices(id) ON DELETE CASCADE,
    co2_ppm DOUBLE PRECISION NOT NULL,
    co_ppm DOUBLE PRECISION NOT NULL,
    pm2_5 DOUBLE PRECISION NOT NULL,
    temperature DOUBLE PRECISION NOT NULL,
    humidity DOUBLE PRECISION NOT NULL,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);